### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by khoi** [Oanhlevn/CatchOppsGame#4]
Thank you for your submission 🙇‍♂️. 

## General comments

- The `obstacle()` function is causing a "jiggering" bug.
- Avoid using [magic numbers](http://wiki.c2.com/?MagicNumber), and use named variables, constants instead.
- Move constants, paths to resources, strings to the very top of the file.

## Nit-picking

1. Variable naming

https://github.com/Oanhlevn/CatchOppsGame/blob/8f3fbda521a10441dad045c9899e39d86172812b/game.js#L19

variables that point to an array should be in plural form. For instance:
```js
let oppImageStocks = []; 
```

https://github.com/Oanhlevn/CatchOppsGame/blob/8f3fbda521a10441dad045c9899e39d86172812b/game.js#L78-79

`directionX` and `directionY` are not concise. We have many objects moving in the game, and as a code reviewer, I'm unsure which object they belong to.

2. Indentation & Code formatting

https://github.com/Oanhlevn/CatchOppsGame/blob/8f3fbda521a10441dad045c9899e39d86172812b/game.js#L80

In Javascript `{` should always stand at the end of the last line. [WHY?](https://coderwall.com/p/j4ub4a/put-your-opening-braces-on-the-same-line-in-js)

**DO**
```js
function sum(a, b) {
	return a + b;
}
```

**DON'T**
```js
function sum(a, b)
{ return a + b;
}
// or
function sum(a, b)
{
	return a + b;
}
```

There are many other formatting problems, I've already submitted a PR https://github.com/Oanhlevn/CatchOppsGame/pull/5/to fix them, you can take a look at the changelog and see what those problems are.

**Comment by chug2k** [comment]
Incredible code review... And PR!!!

**Comment by shitcleaner** [comment]
Very helpful ideas, Khoi!!! Thank you so much!!! I'll check them out and correct them asap.
